### ISSUE TITLE
Module doesn’t work after patch 80 (EU)

### ISSUE THREAD

**Issue by giggin** [teralove/gathering-markers#3]
[07:30:20.099] [mods] ERROR: Module "Gathering Markers" (gathering-markers) could not be loaded!
[07:30:20.103] [mods] ERROR: Please contact the module's author: https://github.com/teralove/gathering-markers/issues
[07:30:20.115] SyntaxError: C:\Users\Matteo\AppData\Local\Programs\CaaliTeraProxy\mods\gathering-markers-master\config.json: Unexpected token ] in JSON at position 180
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:712:27)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at new GatheringMarkers (C:\Users\Matteo\AppData\Local\Programs\CaaliTeraProxy\mods\gathering-markers-master\index.js:4:20)
    at ModuleManager.load (C:\Users\Matteo\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:157:35)
    at installedModules.forEach.mod (C:\Users\Matteo\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:57:22)

It worked fine before the patch. I tried downloading again but it’s still the same

**Comment by trev44** [comment]
yes please help. not working. im eu too

**Comment by a6axa6a** [comment]
> yes please help. not working. im eu too

+1
